## this deploys a single pod with a pod-level GMSA cred spec

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: {{ .TestName }}
  name: {{ .TestName }}
  namespace: {{ .Namespace }}
spec:
  serviceAccountName: {{ .ServiceAccountName }}
  securityContext:
    windowsOptions:
      gmsaCredentialSpecName: {{ index .CredSpecNames 0 }}
{{- if .CredSpecContent }}
      gmsaCredentialSpec: '{{ .CredSpecContent }}'
{{- end }}
  containers:
  - name: nginx
{{- if .Image }}
    image: {{ .Image }}
{{- else }}
    image: registry.k8s.io/pause
{{- end }}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
{{- range $line := .ExtraSpecLines }}
  {{ $line }}
{{- end }}
