apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gmsacredentialspecs.windows.k8s.io
spec:
  group: windows.k8s.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          credspec:
            description: GMSA Credential Spec
            type: object
  names:
    kind: GMSACredentialSpec
    plural: gmsacredentialspecs
  scope: Cluster
