name: build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  unit:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - id: foo
      uses: ./.github/actions/tests
      env:
        T: unit
  integration:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - id: foo
      uses: ./.github/actions/tests
      env:
        T: integration
  deploy_method_download:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - id: foo
      uses: ./.github/actions/tests
      env:
        T: integration
        DEPLOY_METHOD: download
  tolerate_control_plane:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - id: foo
      uses: ./.github/actions/tests
      env:
        T: integration
        NUM_NODES: 0
        EXTRA_GMSA_DEPLOY_ARGS: --tolerate-master
  dry_run_deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - id: foo
      uses: ./.github/actions/tests
      env:
        T: dry_run_deploy
